name: storage-api-sample

services:
  minio:
    build:
      context: .docker/minio/minio
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: "minio.storage-api-sample.dev"
    environment:
      TZ: Asia/Tokyo
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - mode: ingress
        target: 9000
        published: 9000
        protocol: tcp
      - mode: ingress
        target: 9001
        published: 9001
        protocol: tcp
    privileged: true
    restart: always
    tty: true
    volumes:
      - type: bind
        source: .minio/data
        target: /export
        bind:
          create_host_path: true
      - type: bind
        source: .minio/config
        target: /root/.minio
        bind:
          create_host_path: true
    command: server --console-address ":9001" /export

  createbuckets:
    build:
      context: .docker/minio/createbuckets
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: "minio-mc.storage-api-sample.dev"
    environment:
      TZ: Asia/Tokyo
    privileged: true
    restart: always
    tty: true
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add local-bucket http://minio:9000 admin password;
      /usr/bin/mc rm -r --force local-bucket/sample-storage;
      /usr/bin/mc mb local-bucket/sample-storage;
      /usr/bin/mc policy set public local-bucket/sample-storage;
      exit 0;
      "
